names = ['John','Gabriel','Raphaël','Léo','Louis','Lucas','Adam','Arthur','Jules','Hugo'
,'Maël','Liam','Ethan','Paul','Nathan','Gabin','Sacha','Noah','Tom','Mohamed','Aaron'
,'Théo','Noé','Victor','Martin','Mathis','Timéo','Nolan','Enzo','Éden','Axel','Antoine','Léon'
,'Marius','Robin','Valentin','Clément','Baptiste','Tiago','Rayan','Samuel','Amir','Augustin','Naël'
,'Maxime','Maxence','Gaspard','Eliott','Alexandre','Isaac','Mathéo','Yanis','Évan','Simon','Malo','Nino','Marceau','Kylian','Thomas'
,'Ibrahim','Imran','Ayden','Lenny','Camille','Lyam','Kaïs','Oscar','Naïm','Sohan','Côme','Milo','Noa','Ilyes','Noam','Diego','Ismaël'
,'Léandre','Soan','Mathys','Alexis','Lorenzo','Esteban','Owen','Youssef','Ilyan','William','Adrien','Ayoub','Jean','David','Ali','Adem'
,'Wassim','Logan','Sandro','Pablo','Antonin','Joseph','Benjamin','Noham','Kenzo','Emma','Jade','Louise','Alice','Chloé','Lina','Léa','Rose','Anna','Mila','Inès','Ambre','Julia','Mia','Léna','Manon','Juliette','Lou','Camille'
,'Zoé','Lola','Agathe','Jeanne','Lucie','Éva','Nina','Sarah','Romane','Inaya','Charlotte','Léonie','Romy','Adèle','Iris','Louna','Sofia','Margaux','Luna','Olivia'
,'Clémence','Victoria','Léana','Clara','Éléna','Victoire','Aya','Margot','Nour','Giulia','Charlie','Capucine','Mya','Mathilde','Lana','Anaïs','Lilou','Alicia','Théa'
,'Gabrielle','Lya','Yasmine','Maëlys','Assia','Apolline','Élise','Alix','Emy','Lise','Elsa','Lily','Lyana','Lisa','Noémie','Marie','Roxane','Lyna','Héloïse','Candice','Valentine'
,'Zélie','Maya','Soline','Maria','Célia','Maëlle','Emmy','Éléna','Faustine','Salomé','Lila','Louane','Alya','Thaïs','Constance','Laura','Mélina','Livia','Amelia','Océane','Sara']

btmakers = ['Bokusan','Zeyn','Malkrich','Costo','Pprod','Kezah','Ysos','Pandrezz','2ruty','Nausaah','Origami','KLM','Flem','Dany synthé','Skread','Askil','Krono','Born Hero','Yusei','nat','RAD&CO','Keido','EasyDew','Seezy']

rappeurs = ['Lino',
'Shurik’n',
'Akhenaton',
'Oxmo Puccino',
'Booba',
'Nakk Mendosa',
'Fabe',
'Le Rat Luciano',
'Ill',
'Dany Dan',
'Médine',
'Kery James',
'Alpha Wann',
'SCH',
'OrelSan',
'Nekfeu',
'MC Solaar',
'Lomepal',
'Scylla',
'Salif',
'Nepal',
'Lalcko',
'Damso',
'Alkpote',
'Isha',
'Nubi',
'Kohndo',
'Caballero',
'JeanJass',
'Kaaris',
'Veust Lyricist',
'Joe Lucazz',
'Veerus',
'Infinit\'',
'Flynt',
'Vald',
'A2H',
'Ali',
'Youssoupha',
'Dinos',
'Georgio',
'Guizmo',
'Loud',
'Keroué',
'Vidji',
'Hi‐Fi',
'Disiz',
'Espiiem',
'Sofiane',
'Freeze Corleone',
'Dosseh',
'Keny Arkana',
'Sopico',
'Deen Burbigo',
'Jazzy Bazz',
'Dixon',
'PNL',
'Gaël Faye',
'Lefa',
'Kool Shen',
'Ol’ Kainry',
'Don Choa',
'Le Connaisseur',
'Josman',
'Despo Rutti',
'Heskis',
'S.Pri Noir',
'Krisy',
'R.E.D.K',
'Hugo TSR',
'Tiers Monde',
'Gringe',
'Swift Guad',
'Passi',
'Areno Jaz',
'Mokless\'',
'Limsa',
'Tunisiano',
'Aketo',
'Nemir',
'Koriass',
'Prince Waly',
'Gros Mo',
'Kekra',
'Casey',
'Swing',
'Ateyaba',
'Karlito',
'Roméo Elvis',
'Rohff',
'Eden Dillinger',
'PLK',
'Waltmann',
'Vicelow',
'Doums',
'Zoxea',
'Brav',
'Calbo',
'Hayce Lemsi',
'Senamo',
'Seth Gueko',
'Hamza',
'Demi Portion',
'So\'clock',
'Blacko',
'Sinik',
'Pit Baccardi',
'Sat l\'artificier',
'Seyté',
'Taipan',
'Suik\'On Blaze AD',
'Furax Barbarossa',
'Taïro',
'Koma',
'Spider Zed',
'Framal',
'Ladea',
'B-Lel',
'Iron Sy',
'James Deano',
'Fayçal',
'Primero',
'Gracy Hopkins',
'Sneazzy',
'luXe',
'Grems',
'Sadek',
'Davodka',
'Ynnek',
'Faf Larage',
'Tito Prince',
'Esso Luxueux',
'Oumar',
'Maître Gims',
'Barack adama',
'Escobar Macson',
'Vesti',
'Eli MC',
'Tonio MC',
'Kobo',
'Lesram',
'Ichon',
'Makala',
'Dimeh',
'Slimka',
'Zoonard',
'Orus',
'Nikkfurie',
'Ninho']
